### ISSUE TITLE
unhandled exception attempting to expand addon summary

### ISSUE THREAD

**Issue by jet81** [ogri-la/strongbox#169] opened 2020-08-01 16:12 UTC
OS: POP_OS! 20.04
Java: openJDK-8

I was updating addons when I received this.

````
2020-08-01 16:05:30.097 pop-os INFO [strongbox.core:822] - checking for updates
2020-08-01 16:05:36.165 pop-os WARN [strongbox.http:166] - failed to download file 'https://addons-ecs.forgesvc.net/api/v2/addon/281321': Gateway Time-out (HTTP 504)
2020-08-01 16:05:36.166 pop-os ERROR [strongbox.catalogue:38] - unhandled exception attempting to expand addon summary
                              java.lang.Thread.run              Thread.java:  748
java.util.concurrent.ThreadPoolExecutor$Worker.run  ThreadPoolExecutor.java:  624
 java.util.concurrent.ThreadPoolExecutor.runWorker  ThreadPoolExecutor.java: 1149
               java.util.concurrent.FutureTask.run          FutureTask.java:  266
                                               ...                               
               clojure.core/binding-conveyor-fn/fn                 core.clj: 2030
                         strongbox.ui.gui/async/fn                  gui.clj:  111
                 strongbox.core/install-update-all                 core.clj: 1174
                                               ...                               
                            strongbox.core/refresh                 core.clj: 1108
                            strongbox.core/refresh                 core.clj: 1129
                  strongbox.core/check-for-updates                 core.clj:  823
                                 clojure.core/mapv                 core.clj: 6903
                               clojure.core/reduce                 core.clj: 6827
                                               ...                               
                              clojure.core/mapv/fn                 core.clj: 6912
                   strongbox.core/check-for-update                 core.clj:  811
             strongbox.core/expand-summary-wrapper                 core.clj:  804
                                               ...                               
           strongbox.core/affects-addon-wrapper/fn                 core.clj:  369
                                clojure.core/apply                 core.clj:  667
                                               ...                               
                strongbox.catalogue/expand-summary            catalogue.clj:   30
           strongbox.curseforge-api/expand-summary       curseforge_api.clj:  104
                         strongbox.utils/from-json                utils.clj:  299
                                               ...                               
                        clojure.data.json/read-str                 json.clj:  278
                        clojure.data.json/read-str                 json.clj:  282
java.lang.ClassCastException: clojure.lang.PersistentArrayMap cannot be cast to java.lang.String

2020-08-01 16:05:36.182 pop-os ERROR [strongbox.catalogue:39] - please report this! https://github.com/ogri-la/strongbox/issues
2020-08-01 16:05:39.727 pop-os INFO [strongbox.core:827] - 14 addons checked, 2 updates available
````

**Comment by torkus** [comment] 2020-08-02 00:43
Thanks for opening an issue.

It looks like the core of the issue is this:

> failed to download file 'https://addons-ecs.forgesvc.net/api/v2/addon/281321': Gateway Time-out (HTTP 504)

which is a transient failure with Curseforge. Is it working for you now or are you still getting that error?

This case definitely needs better handling than a stacktrace so I'll leave it open.

**Comment by torkus** [comment] 2020-08-08 01:33
Improved handling for Curseforge 500/502/504 errors will be in the next release. 

Thanks again for opening the ticket.

**Closed** 2020-08-09 04:16 UTC
Labels: bug, fixed
