### ISSUE TITLE
links do not open in strongbox 1.0.0 (they work in wowman)

### ISSUE THREAD

**Issue by tstirrat** [ogri-la/strongbox#157] opened 2020-06-15 18:19 UTC
clicking the curseforge, tuk etc links works in wowman 0.12.5, but not in strongbox.

the log output says the link is being opened but they do not actually open:

<img width="676" alt="Screen Shot 2020-06-15 at 11 17 09 AM" src="https://user-images.githubusercontent.com/702990/84691993-fcd30900-aef9-11ea-941a-ce4149ccbd31.png">

**Comment by torkus** [comment] 2020-06-16 01:00
Thanks for opening this issue, @tstirrat , I appreciate it.

I encountered this about two days ago and figured it was just my weird computer setup so I'm very glad it's an actual problem.

I'll add it to the TODO list and it should make it in to the 1.1.0 release before the end of the month.

**Comment by tstirrat** [comment] 2020-06-17 17:07
No probs, I thought the same thing re local environment, but decided to downgrade just in case it was a bug.

**Comment by torkus** [comment] 2020-06-19 14:15
Bug [has been fixed](https://github.com/ogri-la/strongbox/commit/872ca3ca7b87f24e0d4177897746eb63f75b01d5). It was caused by a bulk find+replace operation. I'll leave this ticket open until it is released.

**Comment by torkus** [comment] 2020-06-27 10:46
This fix has just been released as part of 1.1.0, thank you for opening a ticket for it.

**Closed by torkus** 2020-06-27 10:46 UTC
Labels: bug, fixed

**Comment by tstirrat** [comment] 2020-06-28 15:57
Thanks!
