### ISSUE TITLE
Strongbox detecting Leatrix Plus, Maps as client 1.13.5 compatible

### ISSUE THREAD

**Issue by rainecheck** [ogri-la/strongbox#243] opened 2021-02-21 10:33 UTC
**Describe the bug**

Strongbox generating `no match!` statements from Leatrix Plus and Maps. Appears to be a mismatch in the `release-label` - the API call is listing 1.13.5, but the addons (as per the curseforge.com Files page) are set for 1.13.6. Uncertain why Strongbox would be expecting it to match 1.13.5.

Looks like when right clicking and checking Releases, it's listed at 1.13.5 there too.
Persists on a HTTP cache clear, and is still present even after a Catalogue clear

**To Reproduce**

 - Attempt to update Leatrix Plus or Leatrix Maps. INFO logs are posted about mismatches in the bottom Log panel, and in console
 - Rightclick the addon line and check Releases. Lists client version compat as 1.13.5

**Expected behavior**

Strongbox should be detecting the client version of these addons as 1.13.6

Message logs:

```
2021-02-21 10:23:25.329 svirfneblin WARN [strongbox.core:796] - deleting http cache
2021-02-21 10:23:32.433 svirfneblin INFO [strongbox.core:489] - loading installed addons: /ssd/battlenet/drive_c/Program Files (x86)/World of Warcraft/_classic_/Interface/AddOns
2021-02-21 10:23:32.434 svirfneblin INFO [strongbox.core:667] - matching 50 addons to catalogue
2021-02-21 10:23:32.702 svirfneblin INFO [strongbox.core:744] - checking for updates
2021-02-21 10:23:41.590 svirfneblin INFO [strongbox.curseforge-api:112] - no match! {:download-url "https://edge.forgecdn.net/files/3208/91/Leatrix_Maps-1.13.93.zip", :version "1.13.93", :release-label "[WoW 1.13.5] Leatrix_Maps-1.13.93", :game-track :classic, :interface-version 11300} {:download-url "https://edge.forgecdn.net/files/3198/614/Leatrix_Maps-1.13.92.zip", :version "Leatrix_Maps-1.13.92", :release-label "[WoW 1.13.6] Leatrix_Maps-1.13.92", :interface-version 11300, :game-track :classic}
2021-02-21 10:23:41.940 svirfneblin INFO [strongbox.curseforge-api:112] - no match! {:download-url "https://edge.forgecdn.net/files/3208/90/Leatrix_Plus-1.13.93.zip", :version "1.13.93", :release-label "[WoW 1.13.5] Leatrix_Plus-1.13.93", :game-track :classic, :interface-version 11300} {:download-url "https://edge.forgecdn.net/files/3198/610/Leatrix_Plus-1.13.92.zip", :version "Leatrix_Plus-1.13.92", :release-label "[WoW 1.13.6] Leatrix_Plus-1.13.92", :interface-version 11300, :game-track :classic}
2021-02-21 10:24:03.903 svirfneblin INFO [strongbox.core:749] - 50 addons checked, 0 updates available
```

**Comment by torkus** [comment] 2021-02-21 14:06
Sorry for the confusion, I accidentally left a debug statement in. 

This is a duplicate of https://github.com/ogri-la/strongbox/issues/240

What it is doing is looking for the current release in the list of previous releases from Curseforge. The data downloaded from Curseforge is just a summary but there are multiple sections to it. There is detailed data in the latest release section and there is a section with the latest releases by previous versions of WoW. Often the latest release of an addon is also the latest release for the current game version, but not always. To avoid duplicates in the 'releases' menu, I compare the download URLs of the releases in the two sections and remove one.

It really isn't anything to be concerned. I was going to wait for the inevitable bug to come along before doing a patch release and including a fix for this but might do one sooner.

**Closed by torkus** 2021-02-21 14:06 UTC
Labels: bug
