### ISSUE TITLE
Ignore alpha, beta (etc) builds in github sources

### ISSUE THREAD

**Issue by rainecheck** [ogri-la/strongbox#329] opened 2022-01-17 00:04 UTC
With moving away from Curseforge, I've been moving as many sources as possible towards Github etc (at least, until wago support comes in). It's likely this request should have a larger scope, but I'll target it at this for example. This is the current Github releases for Leatrix Plus for TBC:
![image](https://user-images.githubusercontent.com/33798530/149683518-bc800596-68ef-4a70-b3eb-13c9ddf28612.png)

These alphas are not stable, and not desirable for standard users. Having some way to filter out particular releases such as "alpha", "beta", "test" etc would be good for usability of Github sources.

**Comment by torkus** [comment] 2022-01-17 21:59
hey @rainecheck , good to hear from you.

Strongbox has always filtered out the alpha/beta/no-lib releases but it's always relied on the addon host or the author to mark the release as such.

Looking at https://github.com/leatrix/leatrix-plus-bcc/releases I can see that they *are* marked as a pre-release... which is weird because strongbox is also definitely removing prereleases and drafts: https://github.com/ogri-la/strongbox/blob/develop/src/strongbox/github_api.clj#L255-L258

I'm betting it's a bug in my code. Thanks for raising the issue! 

Regarding this:

> (at least, until wago support comes in)

The wowup addon manager appears to have [come to a deal with wago.io](https://addons.wago.io/blog/wowup_announcement) for access to their addons and it involves serving advertisements to it's users. And that is something that won't ever happen with strongbox.

I know that with curseforge support going away strongbox becomes even more niche. I also know that not everybody feels as strongly as I do about user and data privacy and Free software. You're one of the earliest strongbox users, @rainecheck, and I appreciate your patronage these last years, but if you need to jump ship to an addon manager with a larger catalogue available to it I don't mind (I'd miss you of course ;). I'm not in this for a large user base or esteem or anything like that, just good software and good ethics.

**Comment by rainecheck** [comment] 2022-01-17 23:55
Appreciate the thoughts, and the great application's usefulness over the ...years?. I haven't made any decisions, but those things are also quite important to me too, so it's not an obvious decision to me either way.

On a similar topic, is strongbox not picking up the `-bcc` release from [WIM](https://github.com/Legacy-of-Sylvanaar/wow-instant-messenger/releases) potentially a similar issue? Or is that a legit "this release isn't done in the way our github parsing libs were expecting"?

**Comment by torkus** [comment] 2022-01-18 08:32
> On a similar topic, is strongbox not picking up the -bcc release from WIM potentially a similar issue? Or is that a legit "this release isn't done in the way our github parsing libs were expecting"?

definitely looks buggy, I'm getting some unexpected behaviour from it as well. I'll investigate

**Comment by torkus** [comment] 2022-01-18 11:36
ok, [solved first problem](https://github.com/ogri-la/strongbox/pull/330), lets see if I can figure out WIM now.

**Comment by torkus** [comment] 2022-01-18 12:24
Regarding the second problem, I think it's a two part problem, one of which is a caching issue.

I'm not sure what process you went through to install WIM but it's not the `-bcc` version you want, right?

Could you try this for me, please:

1. If you don't care about the addon zip files, `Cache -> Clear addon zips`.
2. If you *do* care about zips, then navigate to your addons directory and delete the `wowinstantmessenger--3-9-4.zip` file.
3. ensure the game track for your addon directory is set to `Classic (TBC)`
4. right-click `wow-instant-messenger` and then click `Re-install`

**Comment by torkus** [comment] 2022-01-20 13:03
4.9.1 has just been released. Pre-releases are now removed from available github releases and the weirdness with updates not being detected is also fixed.

Please let me know if this doesn't solve your problem(s).

**Closed by torkus** 2022-01-20 13:03 UTC
Labels: bug
