### ISSUE TITLE
Does not download classic version of Elvui

### ISSUE THREAD

**Issue by Ironlenny** [ogri-la/strongbox#143] opened 2020-05-05 04:34 UTC
I have installed Elvui through wowman, and it will only install the retail version even though I have classic selected.

**Comment by torkus** [comment] 2020-05-05 13:24
thank you for raising the issue, @Ironlenny , I'll look into it.

**Comment by torkus** [comment] 2020-05-07 14:10
I think I can see your problem.

1. I installed the classic ElvUI (https://www.tukui.org/classic-addons.php?id=2) using wowman. That gives me this:

![Screenshot at 2020-05-07 23-36-20](https://user-images.githubusercontent.com/48790775/81303986-974e5a00-90bb-11ea-9229-055a224ca575.png)

2. I switch the game track from `classic` to `retail` and I can see there is an update available for retail

![Screenshot at 2020-05-07 23-37-29](https://user-images.githubusercontent.com/48790775/81304130-cf559d00-90bb-11ea-8dfb-ff04dedbd85d.png)

3. clicking `update all` (or even right-clicking and selecting `update`) it does something but goes back to the screenshot in point 2, indicating an update is available for `retail` but not having installed it.

Does this sound about right? Or the inverse, you installed retail and now classic won't install?

**Comment by torkus** [comment] 2020-05-14 12:30
> Or the inverse, you installed retail and now classic won't install?

I've just tried the inverse and it behaves differently, displaying no updates available at all. I don't know the *exact* cause yet, but I think these are two separate problems and both are caused by me trying to treat the two Tukui catalogues (retail and classic) as a single one that can be switched between with the game track (retail/classic) dropdown at the top when really there is no mapping between ElvUI in the classic catalogue and Elvui in the retail catalogue. And they both unzip to the samedir :(

**Comment by Ironlenny** [comment] 2020-05-15 02:05
I don't run retail. I only use classic.

**Comment by torkus** [comment] 2020-06-26 13:20
Sorry for the long delay in getting this bug fixed, I was eager to get the name change and the `1.0.0` release out the door.

I have a candidate `1.1.0` release below with the fix in it if you'd like to test it and make sure it works for you:

---

[strongbox-1.1.0-unreleased-standalone.jar.zip](https://github.com/ogri-la/strongbox/files/4837096/strongbox-1.1.0-unreleased-standalone.jar.zip)
sha256: 8a34108f4110de638ce0d747a4f269ce560ef49bcff4acf9ae4c00eacd3a8f0f

---

You can run it with `java -jar strongbox-1.1.0-unreleased-standalone.jar.zip`.

This is fixed only for `strongbox` and won't see a backport to `wowman`.

**Comment by torkus** [comment] 2020-06-27 10:47
This fix has just been released as part of 1.1.0, thank you for opening a ticket. Please re-open the ticket if you feel it's still not behaving as it should be.

**Closed by torkus** 2020-06-27 10:47 UTC
Labels: bug, fixed
